ACHGateway:
  Admin:
    BindAddress: ":9494"
  Inbound:
    HTTP:
      BindAddress: ":8484"
    ODFI:
      Publishing:
        Kafka:
          brokers:
            - kafka1:9092
          key: admin
          secret: secret
          tls: false
          topic: "ach.odfi-files"
      Interval: "1m"
      Processors:
        Corrections:
          Enabled: true
        Prenotes:
          Enabled: true
        Returns:
          Enabled: true
      ShardNames:
        - "testing"
      Storage:
        Directory: "./storage-1/"
        CleanupLocalDirectory: true
  Sharding:
    Shards:
      - name: "testing"
        cutoffs:
          timezone: "America/Los_Angeles"
          windows:
            - "10:30"
            - "14:00"
        uploadAgent: "local-ftp"
        output:
          format: "nacha"
    Mappings:
      "foo": "testing"
    Default: "testing"
  Upload:
    agents:
      - id: "local-ftp"
        ftp:
          hostname: "ftp:2121"
          username: "admin"
          password: "123456"
        paths:
          inbound: "/returned/"
          outbound: "/outbound/"
          reconciliation: "/reconciliation/"
          return: "/returned/"
    merging:
      directory: "./storage-1/"
