version: '3.7'

services:
  achgateway:
    image: moov/achgateway:latest
    ports:
      - "8484:8484"
      - "9494:9494"
    networks:
      - intranet
    volumes:
      - "./:/conf/"
    environment:
      APP_CONFIG: "/conf/config.yml"
    depends_on:
      ftp:
        condition: service_started
      kafka1:
        condition: service_healthy

  ftp:
    image: moov/fsftp:v0.2.0
    ports:
      - "2121:2121"
      - "30000-30009:30000-30009"
    networks:
      - intranet
    volumes:
      - "../../testdata/ftp-server:/data"
    command:
      - "-host=0.0.0.0"
      - "-root=/data"
      - "-user=admin"
      - "-pass=123456"
      - "-passive-ports=30000-30009"

  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    networks:
      - intranet
    environment:
      CLIENT_JVMFLAGS: "-Xms128m -Xmx128m"
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "2181"]
      start_period: 5s
      interval: 5s
      timeout: 2s
      retries: 20

  kafka1:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ach.outgoing-files:1:1,ach.odfi-file-events:1:1"
      KAFKA_HEAP_OPTS: "-Xms128m -Xmx256m"
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092,OUTSIDE://:9093
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka1.:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    networks:
      - intranet
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  intranet: {}
