version: '3.7'

services:
  achgateway:
    image: moov/achgateway:latest
    ports:
      - "8484:8484"
      - "9494:9494"
    networks:
      - intranet
    volumes:
      - "./:/conf/"
    environment:
      APP_CONFIG: "/conf/config.yml"
    depends_on:
      - ftp

  ftp:
    image: moov/fsftp:v0.2.0
    ports:
      - "2121:2121"
      - "30000-30009:30000-30009"
    networks:
      - intranet
    volumes:
      - "../../testdata/ftp-server:/data"
    command:
      - "-host=0.0.0.0"
      - "-root=/data"
      - "-user=admin"
      - "-pass=123456"
      - "-passive-ports=30000-30009"

networks:
  intranet: {}
