# generated-from:1d9b3d94f4b0f679e8204c4f14fd573e2c00d860e17d10925ff98c096101bc5e DO NOT REMOVE, DO UPDATE

version: '3.7'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=achgateway
    - MYSQL_USER=achgateway
    - MYSQL_PASSWORD=achgateway
    - MYSQL_ROOT_PASSWORD=root
    networks:
    - intranet
    tmpfs: # Run this mysql in memory as its used for testing
      - /var/lib/mysql

  consul-server:
    image: hashicorp/consul:1.9.3
    container_name: consul-server
    restart: always
    volumes:
     - ./dev/consul/server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:1.9.3
    container_name: consul-client
    restart: always
    volumes:
     - ./dev/consul/client.json:/consul/config/client.json:ro
    networks:
      - consul
    command: "agent"

  ftp:
    image: moov/fsftp:v0.2.0
    ports:
      - "2121:2121"
      - "30000-30009:30000-30009"
    volumes:
      - "./testdata/ftp-server:/data"
    command:
      - "-host=0.0.0.0"
      - "-root=/data"
      - "-user=admin"
      - "-pass=123456"
      - "-passive-ports=30000-30009"

networks:
  intranet: {}
  consul:
    driver: bridge
