# generated-from:1d9b3d94f4b0f679e8204c4f14fd573e2c00d860e17d10925ff98c096101bc5e DO NOT REMOVE, DO UPDATE

version: '3.7'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=achgateway
      - MYSQL_USER=achgateway
      - MYSQL_PASSWORD=achgateway
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - intranet
    tmpfs: # Run this mysql in memory as its used for testing
      - /var/lib/mysql

  consul-server:
    image: hashicorp/consul:1.10
    container_name: consul-server
    restart: always
    volumes:
      - ./dev/consul/server.json:/consul/config/server.json:ro
      - ./dev/consul/certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8501:8501"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  ftp:
    image: moov/fsftp:v0.2.0
    ports:
      - "2121:2121"
      - "30000-30009:30000-30009"
    volumes:
      - "./testdata/ftp-server:/data"
    command:
      - "-host=0.0.0.0"
      - "-root=/data"
      - "-user=admin"
      - "-pass=123456"
      - "-passive-ports=30000-30009"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka:2.13-2.6.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: notify.kafka.v1:1:1,test1:1:1
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost.:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./testdata/kafka/kafka_server_jaas.conf:/opt/kafka/kafka_server_jaas.conf
    tmpfs: # Run this mysql in memory as its used for testing
      - /tmp/kafka-logs

networks:
  intranet: {}
  consul:
    driver: bridge
