ACHGateway:
  Admin:
    BindAddress: ":9494"
  Inbound:
    HTTP:
      BindAddress: ":8484"
  Shards:
    - name: "testing"
      cutoffs:
        timezone: "America/Los_Angeles"
        windows:
          - "13:47"
      uploadAgent: "local-ftp"
      output:
        format: "nacha"
  Upload:
    agents:
      - id: "local-ftp"
        ftp:
          hostname: "127.0.1:2121"
          username: "admin"
          password: "123456"
        paths:
          inbound: "/returned/"
          outbound: "/outbound/"
          reconciliation: "/reconciliation/"
          return: "/returned/"
  Database:
    DatabaseName: "achgateway"
    MySQL:
      Address: "tcp(localhost:3306)"
      User: "achgateway"
      Password: "achgateway"
